source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod "AFNetworking", "~> 2.0"
pod 'Masonry'
pod 'ArcGIS-Runtime-SDK-iOS'
pod 'MRProgress', '~> 0.8.2'
pod "RMDateSelectionViewController", "~> 2.0.3"
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'Toast', '~> 3.0'
pod 'KLCPopup', '~> 1.0'
pod 'TOWebViewController', '~> 2.2.3'
pod 'SocketRocket', '~> 0.4.2'
pod 'SocketRocket', '~> 0.4.2'
pod 'MarqueeLabel', '~> 2.5.0'
pod 'FMDB', '~> 2.6'
pod 'SDWebImage', '~> 3.7.5'
